



        # TODO: START TABLE

        # start QTableWidget
        # self.tabPayment_QTW = QtWidgets.QTableWidget(self.BottomBox)
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.tabPayment_QTW.sizePolicy().hasHeightForWidth())
        # self.tabPayment_QTW.setSizePolicy(sizePolicy)
        # self.tabPayment_QTW.setStyleSheet("")
        # self.tabPayment_QTW.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        # self.tabPayment_QTW.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        # self.tabPayment_QTW.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        # self.tabPayment_QTW.setShowGrid(True)
        # self.tabPayment_QTW.setWordWrap(True)
        # self.tabPayment_QTW.setRowCount(4)
        # self.tabPayment_QTW.setObjectName("tabPayment_QTW")
        # self.tabPayment_QTW.setColumnCount(4)
        # item = QtWidgets.QTableWidgetItem()
        # self.tabPayment_QTW.setVerticalHeaderItem(0, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tabPayment_QTW.setVerticalHeaderItem(1, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tabPayment_QTW.setVerticalHeaderItem(2, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tabPayment_QTW.setVerticalHeaderItem(3, item)
        # item = QtWidgets.QTableWidgetItem()
        # item.setTextAlignment(QtCore.Qt.AlignCenter)
        # font = QtGui.QFont()
        # font.setPointSize(14)
        # font.setBold(True)
        # font.setWeight(75)
        # item.setFont(font)
        # self.tabPayment_QTW.setHorizontalHeaderItem(0, item)
        # item = QtWidgets.QTableWidgetItem()
        # item.setTextAlignment(QtCore.Qt.AlignCenter)
        # font = QtGui.QFont()
        # font.setPointSize(14)
        # font.setBold(True)
        # font.setWeight(75)
        # item.setFont(font)
        # self.tabPayment_QTW.setHorizontalHeaderItem(1, item)
        # item = QtWidgets.QTableWidgetItem()
        # item.setTextAlignment(QtCore.Qt.AlignCenter)
        # font = QtGui.QFont()
        # font.setPointSize(14)
        # font.setBold(True)
        # font.setWeight(75)
        # item.setFont(font)
        # self.tabPayment_QTW.setHorizontalHeaderItem(2, item)
        # item = QtWidgets.QTableWidgetItem()
        # item.setTextAlignment(QtCore.Qt.AlignCenter)
        # font = QtGui.QFont()
        # font.setPointSize(14)
        # font.setBold(True)
        # font.setWeight(75)
        # item.setFont(font)
        # self.tabPayment_QTW.setHorizontalHeaderItem(3, item)
        # item = QtWidgets.QTableWidgetItem()
        # item.setTextAlignment(QtCore.Qt.AlignCenter)
        # brush = QtGui.QBrush(QtGui.QColor(232, 232, 233))
        # brush.setStyle(QtCore.Qt.NoBrush)
        # item.setBackground(brush)
        # brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        # brush.setStyle(QtCore.Qt.NoBrush)
        # item.setForeground(brush)
        # self.tabPayment_QTW.setItem(0, 0, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tabPayment_QTW.setItem(0, 1, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tabPayment_QTW.setItem(0, 2, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tabPayment_QTW.setItem(0, 3, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tabPayment_QTW.setItem(1, 0, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tabPayment_QTW.setItem(1, 1, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tabPayment_QTW.setItem(1, 2, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tabPayment_QTW.setItem(1, 3, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tabPayment_QTW.setItem(2, 0, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tabPayment_QTW.setItem(2, 1, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tabPayment_QTW.setItem(2, 2, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tabPayment_QTW.setItem(2, 3, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tabPayment_QTW.setItem(3, 0, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tabPayment_QTW.setItem(3, 1, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tabPayment_QTW.setItem(3, 2, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tabPayment_QTW.setItem(3, 3, item)
        # self.tabPayment_QTW.horizontalHeader().setVisible(True)
        # self.tabPayment_QTW.horizontalHeader().setCascadingSectionResizes(True)
        # self.tabPayment_QTW.horizontalHeader().setDefaultSectionSize(200)
        # self.tabPayment_QTW.horizontalHeader().setHighlightSections(True)
        # self.tabPayment_QTW.horizontalHeader().setMinimumSectionSize(23)
        # self.tabPayment_QTW.horizontalHeader().setSortIndicatorShown(True)
        # self.tabPayment_QTW.horizontalHeader().setStretchLastSection(False)
        # self.tabPayment_QTW.verticalHeader().setHighlightSections(True)
        # self.tabPayment_QTW.verticalHeader().setStretchLastSection(False)
        # self.verticalLayout_6.addWidget(self.tabPayment_QTW)
        # end QTableWidget




        # ======================================== #
                        # TABLES ITEM
        # ======================================== #

        # self.tabPayment_QTW.setSortingEnabled(True)
        # item = self.tabPayment_QTW.verticalHeaderItem(0)
        # item.setText(_translate("MainWindow", "1"))
        # item = self.tabPayment_QTW.verticalHeaderItem(1)
        # item.setText(_translate("MainWindow", "2"))
        # item = self.tabPayment_QTW.verticalHeaderItem(2)
        # item.setText(_translate("MainWindow", "3"))
        # item = self.tabPayment_QTW.verticalHeaderItem(3)
        # item.setText(_translate("MainWindow", "4"))
        # item = self.tabPayment_QTW.horizontalHeaderItem(0)
        # item.setText(_translate("MainWindow", "ID"))
        # item = self.tabPayment_QTW.horizontalHeaderItem(1)
        # item.setText(_translate("MainWindow", "ID PARIAGE"))
        # item = self.tabPayment_QTW.horizontalHeaderItem(2)
        # item.setText(_translate("MainWindow", "DATE"))
        # item = self.tabPayment_QTW.horizontalHeaderItem(3)
        # item.setText(_translate("MainWindow", "MONTANT"))
        # __sortingEnabled = self.tabPayment_QTW.isSortingEnabled()
        # self.tabPayment_QTW.setSortingEnabled(False)
        # item = self.tabPayment_QTW.item(0, 0)
        # item.setText(_translate("MainWindow", "33"))
        # item = self.tabPayment_QTW.item(0, 1)
        # item.setText(_translate("MainWindow", "72983"))
        # item = self.tabPayment_QTW.item(0, 2)
        # item.setText(_translate("MainWindow", "21/10/2022"))
        # item = self.tabPayment_QTW.item(0, 3)
        # item.setText(_translate("MainWindow", "450 HTG"))
        # item = self.tabPayment_QTW.item(1, 0)
        # item.setText(_translate("MainWindow", "34"))
        # item = self.tabPayment_QTW.item(1, 1)
        # item.setText(_translate("MainWindow", "47238"))
        # item = self.tabPayment_QTW.item(1, 2)
        # item.setText(_translate("MainWindow", "17/12/2022"))
        # item = self.tabPayment_QTW.item(1, 3)
        # item.setText(_translate("MainWindow", "823 HTG"))
        # item = self.tabPayment_QTW.item(2, 0)
        # item.setText(_translate("MainWindow", "42"))
        # item = self.tabPayment_QTW.item(2, 1)
        # item.setText(_translate("MainWindow", "37238"))
        # item = self.tabPayment_QTW.item(2, 2)
        # item.setText(_translate("MainWindow", "21/01/2023"))
        # item = self.tabPayment_QTW.item(2, 3)
        # item.setText(_translate("MainWindow", "732 HTG"))
        # item = self.tabPayment_QTW.item(3, 0)
        # item.setText(_translate("MainWindow", "32"))
        # item = self.tabPayment_QTW.item(3, 1)
        # item.setText(_translate("MainWindow", "82354"))
        # item = self.tabPayment_QTW.item(3, 2)
        # item.setText(_translate("MainWindow", "15/05/2022"))
        # item = self.tabPayment_QTW.item(3, 3)
        # item.setText(_translate("MainWindow", "50 HTG"))
        # self.tabPayment_QTW.setSortingEnabled(__sortingEnabled)