from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1082, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #1E1E1E;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.MainContainer = QtWidgets.QFrame(self.centralwidget)
        self.MainContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainContainer.setObjectName("MainContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.MainContainer)
        self.verticalLayout_2.setObjectName("verticalLayout_2")


        self.menu_top = QtWidgets.QWidget(self.MainContainer)
        self.menu_top.setStyleSheet("background-color: #2C2C2C;")
        self.menu_top.setObjectName("menu_top")
        self.pushButton = QtWidgets.QPushButton(self.menu_top)
        self.pushButton.setGeometry(QtCore.QRect(376, 120, 79, 24))
        self.pushButton.setStyleSheet("color: #1E1E1E;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.menu_top)
        self.pushButton_2.setGeometry(QtCore.QRect(295, 120, 79, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.menu_top, 0, QtCore.Qt.AlignTop)
        self.bodyContainer = QtWidgets.QWidget(self.MainContainer)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bodyContainer.sizePolicy().hasHeightForWidth())

        self.bodyContainer.setSizePolicy(sizePolicy)
        self.bodyContainer.setStyleSheet("background-color: #2C2C2C;\n"
"")
        self.bodyContainer.setObjectName("bodyContainer")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.bodyContainer)
        self.horizontalLayout.setObjectName("horizontalLayout")


        self.left_aside = QtWidgets.QWidget(self.bodyContainer)
        self.left_aside.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.left_aside.setStyleSheet("background-color: #1E1E1E;")
        self.left_aside.setObjectName("left_aside")


        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.left_aside)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.left_aside)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.left_aside)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_3.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.left_aside)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_3.addWidget(self.pushButton_5)
        self.horizontalLayout.addWidget(self.left_aside, 0, QtCore.Qt.AlignRight)

        # TODO: start central
        # bodyContainer : container parent
        self.central_aside = QtWidgets.QWidget(self.bodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.central_aside.sizePolicy().hasHeightForWidth())
        self.central_aside.setSizePolicy(sizePolicy)
        self.central_aside.setStyleSheet("background-color: #2C2C2C;\n"
"")
        self.central_aside.setObjectName("central_aside")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.central_aside)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        # start head to head
        self.head_to_head = QtWidgets.QWidget(self.central_aside)
        self.head_to_head.setObjectName("head_to_head")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.head_to_head)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.images = QtWidgets.QWidget(self.head_to_head)
        self.images.setMaximumSize(QtCore.QSize(16777215, 201))
        self.images.setStyleSheet("background-image: url(./assets/images/tt.png);\n"
"border-radius: 15px;")
        self.images.setObjectName("images")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.images)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.images)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.verticalLayout_4.addWidget(self.images)
        self.h2h = QtWidgets.QWidget(self.head_to_head)
        self.h2h.setStyleSheet("background-color: #1E1E1E; \n"
"border-radius: 15px;")
        self.h2h.setObjectName("h2h")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.h2h)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineups_container = QtWidgets.QWidget(self.h2h)
        self.lineups_container.setStyleSheet("background-color: #2C2C2C;\n"
"")
        self.lineups_container.setObjectName("lineups_container")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.lineups_container)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.home_team = QtWidgets.QFrame(self.lineups_container)
        self.home_team.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.home_team.setFrameShadow(QtWidgets.QFrame.Raised)
        self.home_team.setObjectName("home_team")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.home_team)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.homteam_button = QtWidgets.QPushButton(self.home_team)
        self.homteam_button.setStyleSheet("color: #fff")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/teams/teams/ajax.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homteam_button.setIcon(icon)
        self.homteam_button.setIconSize(QtCore.QSize(32, 32))
        self.homteam_button.setObjectName("homteam_button")
        self.horizontalLayout_3.addWidget(self.homteam_button)
        self.hometeam_cote = QtWidgets.QLabel(self.home_team)
        self.hometeam_cote.setStyleSheet("color: #E62641;")
        self.hometeam_cote.setObjectName("hometeam_cote")
        self.horizontalLayout_3.addWidget(self.hometeam_cote)
        self.label_2 = QtWidgets.QLabel(self.home_team)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("color: #FAFAFA;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_5.addWidget(self.home_team)
        self.home_team_2 = QtWidgets.QFrame(self.lineups_container)
        self.home_team_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.home_team_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.home_team_2.setObjectName("home_team_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.home_team_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.home_team_2)
        self.label_3.setStyleSheet("color: #FAFAFA;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.hometeam_cote_2 = QtWidgets.QLabel(self.home_team_2)
        self.hometeam_cote_2.setStyleSheet("color: #E62641;")
        self.hometeam_cote_2.setObjectName("hometeam_cote_2")
        self.horizontalLayout_4.addWidget(self.hometeam_cote_2)
        self.pushButton_6 = QtWidgets.QPushButton(self.home_team_2)
        self.pushButton_6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_6.setStyleSheet("color: #fff;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/teams/teams/fcb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon1)
        self.pushButton_6.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_4.addWidget(self.pushButton_6)
        self.horizontalLayout_5.addWidget(self.home_team_2)
        self.verticalLayout_6.addWidget(self.lineups_container)
        self.lineups_container_2 = QtWidgets.QWidget(self.h2h)
        self.lineups_container_2.setStyleSheet("background-color: #2C2C2C;\n"
"")
        self.lineups_container_2.setObjectName("lineups_container_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.lineups_container_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.home_team_3 = QtWidgets.QFrame(self.lineups_container_2)
        self.home_team_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.home_team_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.home_team_3.setObjectName("home_team_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.home_team_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.homteam_button_2 = QtWidgets.QPushButton(self.home_team_3)
        self.homteam_button_2.setStyleSheet("color: #fff")
        self.homteam_button_2.setIcon(icon)
        self.homteam_button_2.setIconSize(QtCore.QSize(32, 32))
        self.homteam_button_2.setObjectName("homteam_button_2")
        self.horizontalLayout_7.addWidget(self.homteam_button_2)
        self.hometeam_cote_3 = QtWidgets.QLabel(self.home_team_3)
        self.hometeam_cote_3.setStyleSheet("color: #E62641;")
        self.hometeam_cote_3.setObjectName("hometeam_cote_3")
        self.horizontalLayout_7.addWidget(self.hometeam_cote_3)
        self.label_4 = QtWidgets.QLabel(self.home_team_3)
        self.label_4.setStyleSheet("color: #FAFAFA;")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.horizontalLayout_6.addWidget(self.home_team_3)
        self.home_team_4 = QtWidgets.QFrame(self.lineups_container_2)
        self.home_team_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.home_team_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.home_team_4.setObjectName("home_team_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.home_team_4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.home_team_4)
        self.label_5.setStyleSheet("color: #FAFAFA;")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.hometeam_cote_4 = QtWidgets.QLabel(self.home_team_4)
        self.hometeam_cote_4.setStyleSheet("color: #E62641;")
        self.hometeam_cote_4.setObjectName("hometeam_cote_4")
        self.horizontalLayout_8.addWidget(self.hometeam_cote_4)
        self.pushButton_7 = QtWidgets.QPushButton(self.home_team_4)
        self.pushButton_7.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_7.setStyleSheet("color: #fff;")
        self.pushButton_7.setIcon(icon1)
        self.pushButton_7.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_8.addWidget(self.pushButton_7)
        self.horizontalLayout_6.addWidget(self.home_team_4)
        self.verticalLayout_6.addWidget(self.lineups_container_2)
        self.verticalLayout_4.addWidget(self.h2h)
        self.horizontalLayout_2.addWidget(self.head_to_head)
        # end head to head


        self.right_details = QtWidgets.QWidget(self.central_aside)
        self.right_details.setStyleSheet("background-color: #1E1E1E; ")
        self.right_details.setObjectName("right_details")
        self.horizontalLayout_2.addWidget(self.right_details)
        self.horizontalLayout.addWidget(self.central_aside)
        self.verticalLayout_2.addWidget(self.bodyContainer)
        # TODO: end cent



        self.verticalLayout.addWidget(self.MainContainer)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Match"))
        self.pushButton_2.setText(_translate("MainWindow", "compte"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_5.setText(_translate("MainWindow", "PushButton"))
        self.homteam_button.setText(_translate("MainWindow", "Ajax"))
        self.hometeam_cote.setText(_translate("MainWindow", "1.5"))
        self.label_2.setText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "0"))
        self.hometeam_cote_2.setText(_translate("MainWindow", "1.5"))
        self.pushButton_6.setText(_translate("MainWindow", "Barca"))
        self.homteam_button_2.setText(_translate("MainWindow", "Ajax"))
        self.hometeam_cote_3.setText(_translate("MainWindow", "1.5"))
        self.label_4.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "0"))
        self.hometeam_cote_4.setText(_translate("MainWindow", "1.5"))
        self.pushButton_7.setText(_translate("MainWindow", "Barca"))
# import images_rc



if __name__ == '__main__':
    app = QtWidgets.QApplication([])
    window = Ui_MainWindow()
    window.setupUi(app)
    app.exec_()

